version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      SQLALCHEMY_DATABASE_URI: "mssql+pyodbc://sa:YourStrong!Pass123@db:1433/OnlineLibraryDB?driver=ODBC+Driver+17+for+SQL+Server"
    depends_on:
      - db
    command: ["sh", "-c", "python init_db.py && gunicorn wsgi:app --bind 0.0.0.0:5000"]

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Pass123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
