"""Initial migration - create tables

Revision ID: c87ec8b7c561
Revises: 
Create Date: 2025-06-26 14:57:30.570372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87ec8b7c561'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Authors',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Books',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=200), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Price', sa.Float(), nullable=False),
    sa.Column('ReleaseDate', sa.Date(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Categories',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Users',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=120), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('BookAuthors',
    sa.Column('BookId', sa.Integer(), nullable=False),
    sa.Column('AuthorId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['AuthorId'], ['Authors.Id'], ),
    sa.ForeignKeyConstraint(['BookId'], ['Books.Id'], ),
    sa.PrimaryKeyConstraint('BookId', 'AuthorId')
    )
    op.create_table('BookCategories',
    sa.Column('BookId', sa.Integer(), nullable=False),
    sa.Column('CategoryId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['BookId'], ['Books.Id'], ),
    sa.ForeignKeyConstraint(['CategoryId'], ['Categories.Id'], ),
    sa.PrimaryKeyConstraint('BookId', 'CategoryId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BookCategories')
    op.drop_table('BookAuthors')
    op.drop_table('Users')
    op.drop_table('Categories')
    op.drop_table('Books')
    op.drop_table('Authors')
    # ### end Alembic commands ###
